// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/types.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Block struct {
	Header               *Header        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Transactions         []*Transaction `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2f027f54ad4521e, []int{0}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type Header struct {
	Version              int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Height               int32    `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	PrevHash             []byte   `protobuf:"bytes,3,opt,name=prevHash,proto3" json:"prevHash,omitempty"`
	RootHash             []byte   `protobuf:"bytes,4,opt,name=rootHash,proto3" json:"rootHash,omitempty"`
	Timestamp            int64    `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2f027f54ad4521e, []int{1}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Header) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Header) GetPrevHash() []byte {
	if m != nil {
		return m.PrevHash
	}
	return nil
}

func (m *Header) GetRootHash() []byte {
	if m != nil {
		return m.RootHash
	}
	return nil
}

func (m *Header) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Transaction struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2f027f54ad4521e, []int{2}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Block)(nil), "Block")
	proto.RegisterType((*Header)(nil), "Header")
	proto.RegisterType((*Transaction)(nil), "Transaction")
}

func init() {
	proto.RegisterFile("proto/types.proto", fileDescriptor_e2f027f54ad4521e)
}

var fileDescriptor_e2f027f54ad4521e = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x31, 0x4f, 0xf3, 0x30,
	0x10, 0x86, 0xe5, 0xe6, 0x4b, 0xfa, 0xe1, 0x84, 0x01, 0x0f, 0xc8, 0x42, 0x48, 0x44, 0x99, 0x2c,
	0x86, 0x04, 0x02, 0x95, 0x60, 0xed, 0xd4, 0xd9, 0x62, 0xea, 0x76, 0x4d, 0xad, 0xda, 0x0a, 0xb1,
	0x23, 0xfb, 0x5a, 0xa9, 0xff, 0x82, 0x9f, 0x8c, 0xea, 0xb6, 0x14, 0x26, 0xfb, 0x79, 0x1f, 0xeb,
	0xf5, 0xe9, 0xe8, 0xcd, 0xe8, 0x1d, 0xba, 0x06, 0xf7, 0xa3, 0x0a, 0x75, 0xbc, 0x57, 0x4b, 0x9a,
	0xce, 0x3f, 0x5d, 0xd7, 0xb3, 0x07, 0x9a, 0x69, 0x05, 0x6b, 0xe5, 0x39, 0x29, 0x89, 0xc8, 0xdb,
	0x69, 0xbd, 0x88, 0x28, 0x4f, 0x31, 0x7b, 0xa2, 0x05, 0x7a, 0xb0, 0x01, 0x3a, 0x34, 0xce, 0x06,
	0x3e, 0x29, 0x13, 0x91, 0xb7, 0x45, 0xfd, 0x71, 0x09, 0xe5, 0x9f, 0x17, 0xd5, 0x17, 0xa1, 0xd9,
	0xb1, 0x84, 0x71, 0x3a, 0xdd, 0x29, 0x1f, 0x8c, 0xb3, 0xb1, 0x3e, 0x95, 0x67, 0x64, 0xb7, 0x87,
	0x7f, 0xcd, 0x46, 0x23, 0x9f, 0x44, 0x71, 0x22, 0x76, 0x47, 0xff, 0x8f, 0x5e, 0xed, 0x16, 0x10,
	0x34, 0x4f, 0x4a, 0x22, 0x0a, 0xf9, 0xc3, 0x07, 0xe7, 0x9d, 0xc3, 0xe8, 0xfe, 0x1d, 0xdd, 0x99,
	0xd9, 0x3d, 0xbd, 0x42, 0x33, 0xa8, 0x80, 0x30, 0x8c, 0x3c, 0x2d, 0x89, 0x48, 0xe4, 0x25, 0xa8,
	0xae, 0x69, 0xfe, 0x6b, 0xde, 0xf9, 0xe3, 0x52, 0x6c, 0x0c, 0xea, 0xed, 0xaa, 0xee, 0xdc, 0xd0,
	0x80, 0x05, 0xbb, 0x87, 0x1e, 0xb6, 0x41, 0x9b, 0xfe, 0xf5, 0xad, 0x51, 0xeb, 0x76, 0x36, 0x7b,
	0x7e, 0x6f, 0xe2, 0xa6, 0x56, 0x59, 0x3c, 0x5e, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x07, 0xa4,
	0x3f, 0xe1, 0x45, 0x01, 0x00, 0x00,
}
